#Configuration parameters for the scan measurement
cfg_motors:
  COM_motors: ["COM4", "COM5", "COM6"]
  z_at_PMT_centre: 70
  PMT_curvature_mapping: "default"

cfg_statistics:
  readouts_per_position: 2 #How often the DAQ is read on a single position (i.e. picoamperemeter measures the current 20 times in a single read, then we would have n*20)
  reference_period: 3 #How many grid positions are scanned between two reference measurements

cfg_DAQ:
  picoscope:
    primary_channel: "A"
    reference_channel: "B"
    sampling_interval: 0.8e-9 #in s, picoscope looks for closest match
    #time window to analyse baseline of scanned PMT, in ns:
    baseline_tmin: 0 #ns
    baseline_tmax: 30 #ns
    #time window to analyse baseline and signal of reference PMT, in ns:
    reference_baseline_tmin: 0 #ns
    reference_baseline_tmax: 30 #ns
    reference_signal_tmin: 60 #ns
    reference_signal_tmax: 90 #ns
  picoamp:
    COM: "COM13"
    count_per_read: 10
    primary_channel: 0
    reference_channel: 1

cfg_grid:
  r_max: 41 #mm
  r_step: 1.25 #mm

cfg_centre_finder:
  ang_step: 45 #step in degrees, if step 30, then a profile at 0, 30, 60, 90...330 will be measured 
  profile_r_start: 42 #mm
  profile_r_stop: 37 #mm
  coarse_step: 2 #mm
  fine_step: 1 #mm
  fit_results_file: "default"
  save_all_profiles: False
  PMT_bulb_radius: 40 #mm

#hydra creates a new folder when running the code and changes the work directory
#You can obviously put whatever path you want here, but if you use relative paths (e.g. "../"), then you have to take this into consideration...
# cfg_paths:
#   data_pulse_mode: data_pulse_mode
#   data_current_mode: data_current_mode
#   centre_finding: centre_finding
  

#Hydra related configs, you can ignore it for measurement configuration.
defaults:
  - override hydra/job_logging: logger_config #Check config/hydra/logger_config.yaml, you can change log level there (default INFO)

