foo: bar

hydra:
  callbacks:
    save_job_info:
      _target_: hydra.experimental.callbacks.PickleJobInfoCallback
  job:
    chdir: true

#Configuration parameters for the scan measurement
cfg_motors:
  COM_motors: ["COM4", "COM5", "COM6"]
  z_at_PMT_centre: 70
  PMT_curvature_mapping: "default"

cfg_DAQ:
  picoscope:
    primary_channel: "A"
    reference_channel: "B"
    sampling_interval: 0.8e-9 #in s, picoscope looks for closest match
    #time window to analyse baseline of scanned PMT, in ns:
    baseline_tmin: 0
    baseline_tmax: 30
    #time window to analyse baseline and signal of reference PMT, in ns:
    reference_baseline_tmin: 0
    reference_baseline_tmax: 30
    reference_signal_tmin: 60
    reference_signal_tmax: 90

  picoamp:
    COM: "COM13"

cfg_grid:
  r_max: 41
  r_step: 1.25

cfg_statistics:
  readouts_per_position: 2 #How often the DAQ is read on a single position (i.e. picoamperemeter measures the current 20 times in a single read, then we would have n*20)
  reference_period: 3 #How many grid positions are scanned between two reference measurements

cfg_centre_finder:
  number_profiles: 6
  profile_r_start: 45
  profile_r_stop: 35
  coarse_step: 1.5
  fine_step: 0.5
  fit_results_file: "default"



#hydra creates a new folder when running the code and changes the work directory
#You can obviously put whatever path you want here, but if you use relative paths (e.g. "../"), then you have to take this into consideration...
# cfg_paths:
#   data_pulse_mode: data_pulse_mode
#   data_current_mode: data_current_mode
#   centre_finding: centre_finding
  

#Hydra related configs, you can ignore it for measurement configuration.
defaults:
  - override hydra/job_logging: logger_config #Check config/hydra/logger_config.yaml, you can change log level there (default INFO)

